ADDRESS_PATH = stellar-deploy-testnet
WASM_DIR = target/wasm32v1-none/release
NETWORK=testnet
ADMIN_ALIAS = alice
ADMIN = $(shell stellar keys address $(ADMIN_ALIAS))
ALICE = $(shell stellar keys address alice)

NATIVE_ADDRESS = CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC #Testnet
#NATIVE_ADDRESS = CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA #Mainnet

# GAS ORACLE
GAS_ORACLE_ADDRESS_PATH = $(ADDRESS_PATH)/gas_orace
GAS_ORACLE_WASM_PATH = $(WASM_DIR)/gas_oracle.wasm
GAS_ORACLE_ADDRESS = $(shell cat $(GAS_ORACLE_ADDRESS_PATH))

# POOL
POOL_WASM_PATH = $(WASM_DIR)/pool.wasm
POOL_USDC_ADDRESS_PATH = $(ADDRESS_PATH)/pool
POOL_USDC_ADDRESS = $(shell cat $(POOL_USDC_ADDRESS_PATH))

# MESSENGER
MESSENGER_WASM_PATH = $(WASM_DIR)/messenger.wasm
MESSENGER_ADDRESS_PATH = $(ADDRESS_PATH)/messenger
MESSENGER_ADDRESS = $(shell cat $(MESSENGER_ADDRESS_PATH))

# BRIDGE
BRIDGE_WASM_PATH = $(WASM_DIR)/bridge.wasm
BRIDGE_ADDRESS_PATH = $(ADDRESS_PATH)/bridge
BRIDGE_ADDRESS = $(shell cat $(BRIDGE_ADDRESS_PATH))

# AUTO DEPOSIT
AUTO_DEPOSIT_WALLET_WASM_PATH = $(WASM_DIR)/auto_deposit_wallet.wasm
AUTO_DEPOSIT_WALLET_WASM_HASH_PATH = $(ADDRESS_PATH)/auto_deposit_wallet_wasm_hash
AUTO_DEPOSIT_WALLET_WASM_HASH = $(shell cat $(AUTO_DEPOSIT_WALLET_WASM_HASH_PATH))

AUTO_DEPOSIT_FACTORY_WASM_PATH = $(WASM_DIR)/auto_deposit_factory.wasm
AUTO_DEPOSIT_FACTORY_ADDRESS_PATH = $(ADDRESS_PATH)/auto_deposit_factory
AUTO_DEPOSIT_FACTORY_ADDRESS = $(shell cat $(AUTO_DEPOSIT_FACTORY_ADDRESS_PATH))

YARO_ADDRESS=CACOK7HB7D7SRPMH3LYYOW77T6D4D2F7TR7UEVKY2TVSUDSRDM6DZVLK # Testnet
USDY_ADDRESS=CAOPX7DVI3PFLHE7637YSFU6TLG6Z27Z5O3M547ANAYXQOAYCYYV6NO6 # Testnet
USDC_ADDRESS=CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA # Testnet

POOL_WASM_PATH = $(WASM_DIR)/pool.wasm

POOL_YARO_ADDRESS_PATH = $(ADDRESS_PATH)/pool_yaro
POOL_YARO_ADDRESS = $$(cat $(POOL_YARO_ADDRESS_PATH))

POOL_USDY_ADDRESS_PATH = $(ADDRESS_PATH)/pool_usdy
POOL_USDY_ADDRESS = $$(cat $(POOL_USDY_ADDRESS_PATH))

POOL_USDC_ADDRESS_PATH = $(ADDRESS_PATH)/pool
POOL_USDC_ADDRESS = $$(cat $(POOL_USDC_ADDRESS_PATH))

#USDC
#TOKEN_ADDRESS=$(USDC_ADDRESS)
#POOL_ADDRESS_PATH=$(POOL_USDC_ADDRESS_PATH)
#POOL_ADDRESS=$(POOL_USDC_ADDRESS)

#YARO
TOKEN_ADDRESS=$(YARO_ADDRESS)
POOL_ADDRESS_PATH=$(POOL_YARO_ADDRESS_PATH)
POOL_ADDRESS=$(POOL_YARO_ADDRESS)

#USDY
#TOKEN_ADDRESS=$(USDY_ADDRESS)
#POOL_ADDRESS_PATH=$(POOL_USDY_ADDRESS_PATH)
#POOL_ADDRESS=$(POOL_USDY_ADDRESS)